### PR TITLE
Add option to abort if newer run started

### PR DESCRIPTION
**Pull request by WIStudent**
I added the new option `abort-on-newer-run`. If it is set to `true`, the current run will be aborted if a previous run is still in progress but a newer run already started running.

```
+-------------------+
|                   |
|                   v
|        previous run in progress?
|         +                     +
|         |                     |
|      No |                     | Yes
|         |                     |
|         v                     v
|     Continue         newer run in progress?
|                        +             +
|                        |             |
|                     No |             | Yes
|                        |             |
|                        v             v
+---------------------+ Wait      Abort current run
```

### CODE REVIEW

**Comment by softprops** [comment]
love the ascii diagram. super helpful to explain. thanks!

**Comment by leviem1** [comment]
Just wanted to let you know that I rebased this in my [fork](https://github.com/sebs-scholarship/turnstyle) in case it's easier to pull that due to the conflicts.

Thanks a lot for the cool feature @WIStudent , I still have yet to fully try it out beyond just rebasing, but this is exactly what I was looking for when I found this project!

**Comment by chadxzs** [comment]
The behavior defined in this PR is how the built-in `concurrency` property on a workflow works. One of the main differentiators between the concurrency property and this action is that this action does not have this behavior.

**Comment by WIStudent** [comment]
Back when I opened this PR Github's own concurrency implementation did not exist yet. Nowadays I am also using the `concurrency` option in my workflows instead of the tunrstyle action. I will close this PR because it is no longer needed.

**Pull request closed without merging**
