### PR TITLE
Upgrade dependencies, add debug logs

### PR DESCRIPTION
**Pull request by roryabraham**
Hello 👋🏼 

We love this action, but we saw some errors with it today. I forked the action and was able to fix it. I'm not sure exactly which of these changes resolved the error(s), but they all seem reasonably beneficial.

- Switch from Node 12 to Node 16
- Upgrade all dependencies to latest
- Fix some resultant TypeScript errors
- Add debug logs

### CODE REVIEW

**Comment by fbuinosquy1985** [comment]
Please merge and release it.

**Comment by roryabraham** [comment]
If you need this fix, you can use my fork in the meantime: https://github.com/roryabraham/turnstyle

**Comment by michaelstepner** [comment]
FYI @fbuinosquy1985 and @roryabraham:

Github has incorporated equivalent functionality to `turnstyle` into the Github Actions spec using the 'concurrency' parameter. `softprops/turnstyle` was developed in 2020 and Github [added the concurrency parameter in 2021](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/).

The native 'concurrency' implementation has additional features beyond what's possible in turnstyle, and it is lower cost: it leaves jobs pending rather than running while they wait for a previous job to end.

**Comment by fbuinosquy1985** [comment]
> FYI @fbuinosquy1985 and @roryabraham:
> 
> Github has incorporated equivalent functionality to `turnstyle` into the Github Actions spec using the 'concurrency' parameter. `softprops/turnstyle` was developed in 2020 and Github [added the concurrency parameter in 2021](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/).
> 
> The native 'concurrency' implementation has additional features beyond what's possible in turnstyle, and it is lower cost: it leaves jobs pending rather than running while they wait for a previous job to end.

yes i know that, but i want to use this anyway

**Comment by michaelstepner** [comment]
> yes i know that, but i want to use this anyway

👍, i expect some other people looking at this PR might not know this package duplicates now-native functionality, so hopefully my comment will be useful to others.

**Comment by dudicoco** [comment]
> FYI @fbuinosquy1985 and @roryabraham:
> 
> Github has incorporated equivalent functionality to `turnstyle` into the Github Actions spec using the 'concurrency' parameter. `softprops/turnstyle` was developed in 2020 and Github [added the concurrency parameter in 2021](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/).
> 
> The native 'concurrency' implementation has additional features beyond what's possible in turnstyle, and it is lower cost: it leaves jobs pending rather than running while they wait for a previous job to end.

@michaelstepner that's incorrect, the native functionality only waits for one job to complete while this action acts as a queue waiting for all previous jobs to complete.

Per the [docs]<https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency>:
> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. **Any previously pending job or workflow in the concurrency group will be canceled.**

**Comment by michaelstepner** [comment]
>  the native functionality only waits for one job to complete while this action acts as a queue waiting for all previous jobs to complete.

Good point @dudicoco! It would be more accurate to say that `concurrency` is not a complete replacement for `turnstyle`:
- There are features in turnstyle not present in concurrency
- There are features in concurrency not present in turnstyle

**Comment by mastery-shaifali-silawat** [comment]
Hi @roryabraham 
Please release it with the latest changes.

**Comment by varunaroratest** [comment]
Hi @softprops 
Please create a release with the latest changes.

**Pull request merged**
