### PR TITLE
feature: wait for queued runs and an option to refresh runs from GitHub API

### PR DESCRIPTION
**Pull request by vigneshmsft**
Hi 👋🏽
This PR adds support to consider `queued` runs in addition to `in_progress` when checking against a list of current runs.

## Problem
When a run is first created in GitHub Actions, the status will be `queued` before moving to `in_progress`
When two runs are triggered within quick succession, 
there is a chance that both the runs are `queued` with only millisecond difference and when this action 
from within the second run tries to fetch a list of `in_progress` runs (where id < itself), the list can be empty because the previous run hasn't still progressed to `in_progress`  in the API results.
We have seen this behaviour multiple times in our workflows.

## Change Proposed
1. Fetch both `queued` and `in_progress` runs
  This would allow the second run to see that a previous run has been queued and it should wait for it to complete.
2. Add `initial-wait-seconds` input parameter
   This adds an option to fetch (again) the list of runs from the GitHub API, if no results are returned during the first poll.

Thanks

rebased: 13-Apr-2021

### CODE REVIEW

**Comment by AmirAvram** [comment]
Any timeline on a merge?
Stumbled upon it to with failure on production deployments (so very critical for us).

**Comment by vigneshmsft** [comment]
not sure why build is failing at fmtcheck step, `npm run fmtcheck` throws no error when running locally.

**Comment by GideonShils** [comment]
Any updates on getting this one merged?

**Review by chenrui333 — APPROVED** [review]
looks like a good feature, need resolve the merge conflict

**Pull request merged**
